export enum LANGUAGES {
  BOSNIAN = 'Bosnian',
  GALICIAN = 'Galician',
  HINDI = 'Hindi',
  ICELANDIC = 'Icelandic',
  MALTESE = 'Maltese',
  SESOTHO_SA_LEBOA = 'Sesotho sa Leboa',
  SETSWANA = 'Setswana',
  SINDHI = 'Sindhi',
  UYGHUR = 'Uyghur',
  ISIZULU = 'isiZulu',
}

export enum STATES {
  LA = 'LA',
  MN = 'MN',
  KS = 'KS',
  MO = 'MO',
  PA = 'PA',
  SD = 'SD',
  CT = 'CT',
  CA = 'CA',
  MS = 'MS',
  TN = 'TN',
  ND = 'ND',
  WA = 'WA',
  KY = 'KY',
  CO = 'CO',
  OR = 'OR',
  FL = 'FL',
  RI = 'RI',
}
